# Generated by Django 5.2.17 on 2026-09-28 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "campaigns",
            "0002_campaign_ops_approved_at_campaign_ops_approved_by_and_more",
        ),
        ("contracts", "0001_initial"),
        ("creators", "0001_initial"),
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for creator"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("withdrawn", "Withdrawn"),
                            ("released", "Released (brand didn't pay in time)"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("creator_fee", models.PositiveIntegerField()),
                ("brand_price", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField()),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decline_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fee", "Fee too low"),
                            ("timing", "Timeline doesn't work"),
                            ("product", "Not a fit for my audience"),
                            ("brand", "Don't want to work with this brand"),
                            ("busy", "Too busy right now"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("decline_note", models.CharField(blank=True, max_length=300)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.agreement",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="matching.matchcandidate",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offers",
                        to="creators.creatorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offering", "Offer sent"),
                            ("accepted", "Accepted, awaiting payment"),
                            ("confirmed", "Paid, in production"),
                            ("unfilled", "No creator available"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="offering",
                        max_length=12,
                    ),
                ),
                ("creator_fee", models.PositiveIntegerField(default=0)),
                ("brand_price", models.PositiveIntegerField(default=0)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("payment_due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="creators.creatorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
