# Generated by Django 5.2.17 on 2026-09-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="creator_brief",
            field=models.JSONField(
                blank=True, default=dict, help_text="Hooks, script, shot list"
            ),
        ),
        migrations.AddField(
            model_name="slot",
            name="review_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="slot",
            name="revisions_used",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="slot",
            name="status",
            field=models.CharField(
                choices=[
                    ("offering", "Offer sent"),
                    ("accepted", "Accepted, awaiting payment"),
                    ("confirmed", "Paid, in production"),
                    ("in_review", "Draft with brand for review"),
                    ("changes_requested", "Changes requested"),
                    ("approved", "Brand approved, waiting for creator's final OK"),
                    ("scheduled", "Scheduled to publish"),
                    ("self_post", "Waiting for creator to post"),
                    ("live", "Live, in verification"),
                    ("verified", "Verified, payout released"),
                    ("on_hold", "On hold: post missing or edited"),
                    ("unfilled", "No creator available"),
                    ("cancelled", "Cancelled"),
                ],
                default="offering",
                max_length=20,
            ),
        ),
    ]
