# Generated by Django 5.2.17 on 2026-09-28 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brands", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("brief_ready", "Brief ready to review"),
                            ("brief_confirmed", "Brief confirmed"),
                            ("shortlisted", "Creators selected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "objective",
                    models.CharField(
                        choices=[
                            ("awareness", "Awareness (reach)"),
                            ("engagement", "Engagement"),
                            ("traffic", "Website traffic"),
                            ("sales", "Sales"),
                            ("content", "Content only (assets for my own channels)"),
                        ],
                        default="awareness",
                        max_length=20,
                    ),
                ),
                ("product_url", models.URLField(blank=True, max_length=1000)),
                (
                    "product_notes",
                    models.TextField(
                        blank=True, help_text="Anything else about the product"
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(blank=True, upload_to="products/%Y/%m/"),
                ),
                (
                    "budget",
                    models.PositiveBigIntegerField(help_text="Paise, excluding GST"),
                ),
                (
                    "creators_wanted",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "deliverable",
                    models.CharField(
                        choices=[
                            ("reel", "Instagram Reel"),
                            ("story", "Instagram Story"),
                            ("post", "Feed post / carousel"),
                        ],
                        default="reel",
                        max_length=10,
                    ),
                ),
                (
                    "target_gender",
                    models.CharField(
                        choices=[
                            ("any", "Any"),
                            ("female", "Mostly women"),
                            ("male", "Mostly men"),
                        ],
                        default="any",
                        max_length=10,
                    ),
                ),
                ("target_cities", models.JSONField(blank=True, default=list)),
                ("languages", models.JSONField(blank=True, default=list)),
                (
                    "content_mode",
                    models.CharField(
                        choices=[
                            ("creator_made", "Creator films it (AI helps with script)"),
                            (
                                "ai_likeness",
                                "AI-assisted with creator's likeness (creator approves)",
                            ),
                        ],
                        default="creator_made",
                        max_length=20,
                    ),
                ),
                ("usage_rights_days", models.PositiveSmallIntegerField(default=90)),
                ("paid_ads_allowed", models.BooleanField(default=True)),
                ("must_say", models.TextField(blank=True)),
                ("must_not_say", models.TextField(blank=True)),
                ("content_deadline", models.DateField(blank=True, null=True)),
                ("margin_bps", models.PositiveIntegerField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="brands.brandprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveSmallIntegerField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("gemini", "AI (Gemini)"),
                            ("rules", "Automatic (rule-based)"),
                            ("edited", "Edited by brand"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="BriefData (see apps.integrations.llm.schema)"
                    ),
                ),
                ("fetch_error", models.CharField(blank=True, max_length=300)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="briefs",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "version"), name="unique_brief_version"
                    )
                ],
            },
        ),
    ]
