# Generated by Django 5.2.17 on 2026-09-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0002_campaign_ops_approved_at_campaign_ops_approved_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("brief_ready", "Brief ready to review"),
                    ("brief_confirmed", "Brief confirmed"),
                    ("shortlisted", "Creators selected"),
                    ("offers_out", "Offers sent"),
                    ("active", "In production"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
