# Generated by Django 5.2.17 on 2026-09-28 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_alter_campaign_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="repeat_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repeats",
                to="campaigns.campaign",
            ),
        ),
    ]
