# Generated by Django 5.2.17 on 2026-09-28 11:12

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("niches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(max_length=200)),
                ("website", models.URLField(blank=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What the brand sells and to whom."
                    ),
                ),
                (
                    "gstin",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[apps.core.validators.validate_gstin],
                    ),
                ),
                (
                    "pan",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[apps.core.validators.validate_pan],
                    ),
                ),
                ("billing_address", models.TextField(blank=True)),
                ("competitors", models.JSONField(blank=True, default=list)),
                (
                    "domain_verification_token",
                    models.CharField(blank=True, max_length=64),
                ),
                ("domain_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Onboarding"),
                            ("pending_review", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("review_note", models.TextField(blank=True)),
                (
                    "niches",
                    models.ManyToManyField(
                        blank=True, related_name="brands", to="niches.niche"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
