# Generated by Django 5.2.17 on 2026-09-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sentreminder"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("last_run_at", models.DateTimeField()),
                ("last_result", models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
