# Generated by Django 5.2.17 on 2026-09-28 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brands", "0001_initial"),
        (
            "campaigns",
            "0002_campaign_ops_approved_at_campaign_ops_approved_by_and_more",
        ),
        ("contracts", "0001_initial"),
        ("creators", "0001_initial"),
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("financial_year", models.CharField(max_length=7, unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_signature", "Awaiting order signature"),
                            ("created", "Awaiting payment"),
                            ("paid", "Paid"),
                            ("failed", "Payment failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="awaiting_signature",
                        max_length=20,
                    ),
                ),
                ("subtotal", models.PositiveBigIntegerField()),
                ("cgst", models.PositiveBigIntegerField(default=0)),
                ("sgst", models.PositiveBigIntegerField(default=0)),
                ("igst", models.PositiveBigIntegerField(default=0)),
                ("total", models.PositiveBigIntegerField()),
                ("provider", models.CharField(max_length=20)),
                (
                    "provider_order_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("provider_payment_id", models.CharField(blank=True, max_length=100)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("lines", models.JSONField(default=list)),
                (
                    "agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.agreement",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="brands.brandprofile",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("held", "Held until post is verified"),
                            ("releasable", "Ready to pay"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="held",
                        max_length=12,
                    ),
                ),
                ("gross", models.PositiveIntegerField(help_text="Creator fee")),
                (
                    "gst",
                    models.PositiveIntegerField(
                        default=0, help_text="Added if the creator is GST-registered"
                    ),
                ),
                ("tds", models.PositiveIntegerField()),
                ("tds_rate_bps", models.PositiveIntegerField()),
                ("net", models.PositiveIntegerField(help_text="gross + gst - tds")),
                (
                    "utr",
                    models.CharField(
                        blank=True, help_text="Bank transfer reference", max_length=40
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="creators.creatorprofile",
                    ),
                ),
                (
                    "slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout",
                        to="offers.slot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("event_id", models.CharField(max_length=100)),
                ("event_type", models.CharField(max_length=60)),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "event_id"), name="unique_webhook_event"
                    )
                ],
            },
        ),
    ]
