# Generated by Django 5.2.17 on 2026-09-28 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0003_slot_creator_brief_slot_review_due_at_and_more"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.PositiveBigIntegerField(
                        help_text="Taxable value refunded (paise)"
                    ),
                ),
                ("cgst", models.PositiveBigIntegerField(default=0)),
                ("sgst", models.PositiveBigIntegerField(default=0)),
                ("igst", models.PositiveBigIntegerField(default=0)),
                ("total", models.PositiveBigIntegerField()),
                ("reason", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Processing"),
                            ("processed", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "provider_refund_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("credit_note_number", models.CharField(max_length=30, unique=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invoicesequence",
            name="series",
            field=models.CharField(default="INV", max_length=8),
        ),
        migrations.AlterField(
            model_name="invoicesequence",
            name="financial_year",
            field=models.CharField(max_length=7),
        ),
        migrations.AddConstraint(
            model_name="invoicesequence",
            constraint=models.UniqueConstraint(
                fields=("series", "financial_year"), name="unique_series_per_fy"
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="payments.order",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="offers.slot",
            ),
        ),
    ]
