# Generated by Django 5.2.17 on 2026-09-28 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("creators", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eligible_count", models.PositiveIntegerField(default=0)),
                (
                    "excluded_counts",
                    models.JSONField(
                        default=dict, help_text="Exclusion reason -> count"
                    ),
                ),
                ("shortage", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaigns.productbrief",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_runs",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[("recommended", "Recommended"), ("backup", "Backup")],
                        max_length=12,
                    ),
                ),
                ("score", models.FloatField()),
                ("components", models.JSONField(default=dict)),
                ("reasons", models.JSONField(default=list)),
                ("creator_fee", models.PositiveIntegerField()),
                ("brand_price", models.PositiveIntegerField()),
                ("selected", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creators.creatorprofile",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="matching.matchrun",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "creator"), name="unique_candidate_per_run"
                    )
                ],
            },
        ),
    ]
