# Generated by Django 5.2.17 on 2026-09-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchrun",
            name="budget",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchrun",
            name="creators_wanted",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchrun",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("initial", "First selection"),
                    ("top_up", "More creators for a running campaign"),
                ],
                default="initial",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="matchrun",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
