# Generated by Django 5.2.17 on 2026-09-28 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("offers", "0003_slot_creator_brief_slot_review_due_at_and_more"),
        ("payments", "0002_refund_invoicesequence_series_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "party",
                    models.CharField(
                        choices=[("brand", "Brand"), ("creator", "Creator")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("off_brief", "Content doesn't follow the brief"),
                            (
                                "unresponsive_creator",
                                "Creator unresponsive or missed the deadline",
                            ),
                            ("post_changed", "Post removed or changed"),
                            ("unresponsive_brand", "Brand unresponsive"),
                            ("scope", "Asked for changes outside the brief"),
                            ("payment", "Payment problem"),
                            ("other", "Something else"),
                        ],
                        max_length=24,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pay_creator", "Creator is paid in full"),
                            ("refund_full", "Brand refunded in full, creator not paid"),
                            ("split", "Partial refund to brand, creator paid the rest"),
                            ("no_change", "No change: campaign continues as normal"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(blank=True, help_text="Shown to both sides"),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.refund",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="offers.slot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "open")),
                        fields=("slot",),
                        name="one_open_dispute_per_slot",
                    )
                ],
            },
        ),
    ]
