# Generated by Django 5.2.17 on 2026-09-28 11:12

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("niches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=120)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("other", "Other / prefer not to say"),
                        ],
                        max_length=10,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=80)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("bio", models.TextField(blank=True)),
                ("ig_username", models.CharField(blank=True, max_length=60)),
                ("ig_user_id", models.CharField(blank=True, max_length=64)),
                ("ig_access_token", apps.core.fields.EncryptedTextField(blank=True)),
                ("ig_token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("ig_connected_at", models.DateTimeField(blank=True, null=True)),
                ("ig_synced_at", models.DateTimeField(blank=True, null=True)),
                ("followers", models.PositiveIntegerField(default=0)),
                (
                    "avg_reach",
                    models.PositiveIntegerField(
                        default=0, help_text="Average reach per recent post"
                    ),
                ),
                (
                    "avg_views",
                    models.PositiveIntegerField(
                        default=0, help_text="Average Reel plays"
                    ),
                ),
                (
                    "engagement_rate",
                    models.FloatField(default=0, help_text="Engagements ÷ reach × 100"),
                ),
                ("audience_female_pct", models.FloatField(default=50)),
                ("audience_india_pct", models.FloatField(default=0)),
                ("audience_top_cities", models.JSONField(blank=True, default=list)),
                (
                    "audience_age",
                    models.JSONField(
                        blank=True, default=dict, help_text='e.g. {"18-24": 40}'
                    ),
                ),
                ("content_keywords", models.JSONField(blank=True, default=list)),
                ("sponsored_posts_30d", models.PositiveSmallIntegerField(default=0)),
                ("authenticity_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "reliability_score",
                    models.FloatField(
                        default=0.7, help_text="0-1, from delivery history"
                    ),
                ),
                ("rate_reel", models.PositiveIntegerField(default=0)),
                ("rate_story", models.PositiveIntegerField(default=0)),
                ("rate_post", models.PositiveIntegerField(default=0)),
                (
                    "red_lines",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="SensitiveCategory values the creator refuses",
                    ),
                ),
                ("allows_ai_likeness", models.BooleanField(default=False)),
                ("max_active_campaigns", models.PositiveSmallIntegerField(default=3)),
                ("on_break", models.BooleanField(default=False)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("pan", apps.core.fields.EncryptedTextField(blank=True)),
                ("pan_last4", models.CharField(blank=True, max_length=4)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("bank_account_name", models.CharField(blank=True, max_length=200)),
                (
                    "bank_account_number",
                    apps.core.fields.EncryptedTextField(blank=True),
                ),
                ("bank_account_last4", models.CharField(blank=True, max_length=4)),
                ("bank_ifsc", models.CharField(blank=True, max_length=11)),
                ("kyc_document", models.FileField(blank=True, upload_to="kyc/%Y/%m/")),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not submitted"),
                            ("pending", "Pending review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="not_submitted",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Onboarding"),
                            ("pending_review", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("review_note", models.TextField(blank=True)),
                (
                    "niches",
                    models.ManyToManyField(
                        blank=True, related_name="creators", to="niches.niche"
                    ),
                ),
                (
                    "primary_niche",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="niches.niche",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
