# Generated by Django 5.2.17 on 2026-09-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorprofile",
            name="ig_needs_reconnect",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="ig_sync_error",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="ig_sync_failures",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
